### ISSUE TITLE
Add 'mailto' to the contact page button

### ISSUE THREAD

**Issue by ericdesj** [ericdesj/csscheduler#4]
Modify the button to, upon clicking it, the user with open an email client to send an email.

http://php.net/manual/en/function.mail.php

**Comment by Blyska** [comment]
I'm giving it a try. Also, awesome design man.

**Comment by ericdesj** [comment]
Still need to get modify some stuff, but it's getting there.

**Comment by ericdesj** [comment]
Used html mailto instead
